name: "publish"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'release type: minor | patch | beta'
        required: true

jobs:
  publish-new-version:
    name: "publish a new version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: npm install
        run: npm ci

      - name: get version list
        run: echo "VERSION_LIST="$(npm view zwltest-package1 versions --json)"" >> $GITHUB_ENV
        # env:
        #     RELEASE_TYPE: ${{ github.event.inputs.release_type }}
      #${{ github.event.inputs.release_type }}
        # run: echo "RELEASE_TYPE=$(npx semver 1.30.0 -i patch)" >> $GITHUB_ENV

      - name: get version
        run: echo "RELEASE_VERSION="$(node script/version.js)"" >> $GITHUB_ENV
        env:
            RELEASE_TYPE: ${{ github.event.inputs.release_type }}

      - name: publish
        run: |
          git config --global user.name 'zwlafk'
          git config --global user.email 'zwlafk@users.noreply.github.com'
          npm config set registry=https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm whoami
          echo "$RELEASE_VERSION"
          lerna version $RELEASE_VERSION --exact --force-publish --yes --no-push
          lerna publish from-package --dist-tag --yes
          git push -o ci.skip --follow-tags --no-verify --atomic
