name: release

on:
  create

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make release
        if: github.event.ref_type == 'tag'
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
            npm install
            node script/release.js
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CHANGELOG_PATH: changelog/index.md, changelog/index-en-US.md
